/** English copy for app PIN (align with business `business/lib/i18n/app-pin-en.ts`). */

export const appPinStrings = {
  setupTitle: 'Create a new PIN',
  setupSubtitle: "Enter a 4-digit code you won't forget",
  confirmTitle: 'Confirm your PIN',
  confirmSubtitle: 'Enter the same 4 digit code again',
  mismatch: 'PINs do not match. Start again.',
  lockWelcome: (name: string) => `Hi${name ? `, ${name}` : ''}`,
  lockEnterPin: 'Enter your 4-digit PIN',
  lockIncorrect: 'Incorrect PIN',
  lockVerifying: 'Verifying…',
  pinSaving: 'Saving your PIN…',
  lockLockedTryMinutes: (m: number) => `PIN locked. Try again in ${m} minute(s).`,
  lockNotYourAccount: 'Not your account?',
  lockLogOut: 'Log out',
  dialogAuthorizeTitle: 'Enter PIN to confirm',
  dialogAuthorizeDesc: 'Enter your 4-digit app PIN to continue.',
  dialogConfirm: 'Confirm',
  dialogCancel: 'Cancel',
  settingsAppPin: 'App PIN',
  forgotPinTitle: 'Forgot PIN?',
  forgotPinBody: 'You will need to sign in with your email and password to set a new PIN.',
  forgotPinSignIn: 'Sign in',
  logOutTitle: 'Log out',
  logOutBody: 'Are you sure you want to log out?',
  errorTitle: 'Error',
  completePinPrompt: 'Please enter a complete 4-digit PIN',
  setupFailed: 'Failed to set up PIN',
  settingsCurrentPin: 'Current PIN',
  settingsNewPin: 'New PIN',
  settingsConfirmNew: 'Confirm new PIN',
  changePinTitle: 'Change PIN',
  changePinNoPinMessage: 'Set up an app PIN first.',
  changePinSuccessBody: 'Your app PIN was updated.',
} as const
