/** @generated by packages/shared/scripts/sync-flags.mjs — do not edit */

/**
 * Web flags are served from `/public/flags/{iso}.png` (see `getFlagPublicUrl`),
 * cached immutably via next.config headers. We intentionally do NOT `require()` the
 * bundled PNGs here: Turbopack (local dev) emits those as runtime requires in the SSR
 * chunk and crashes with "Cannot find module '../../assets/flags/xx.png'". Returning
 * undefined lets `CountryFlag` fall back to the public URL, which works in both
 * Turbopack (dev) and webpack (prod) builds.
 */
export function getFlagBundledSrc(_iso: string): string | undefined {
  return undefined
}
