/** Auto-built from business/lib/countries.ts + office/lib/country-service.ts — do not edit by hand */
import type { FC } from "react"
import type { IconProps } from "nucleo-flags"
import {
  IconAfghanistan,
  IconAlbania,
  IconAlgeria,
  IconAndorra,
  IconAngola,
  IconAntiguaBarbuda,
  IconArgentina,
  IconArmenia,
  IconAustralia,
  IconAustria,
  IconAzerbaijan,
  IconBahamas,
  IconBahrain,
  IconBangladesh,
  IconBarbados,
  IconBelarus,
  IconBelgium,
  IconBelize,
  IconBenin,
  IconBhutan,
  IconBolivia,
  IconBosniaHerzegovina,
  IconBotswana,
  IconBrazil,
  IconBrunei,
  IconBulgaria,
  IconBurkinaFaso,
  IconBurundi,
  IconCambodia,
  IconCameroon,
  IconCanada,
  IconCapeVerde,
  IconCentralAfricanRepublic,
  IconChad,
  IconChile,
  IconChina,
  IconColombia,
  IconComoros,
  IconCostaRica,
  IconCroatia,
  IconCuba,
  IconCyprus,
  IconCzechia,
  IconDemocraticRepublicCongo,
  IconDenmark,
  IconDjibouti,
  IconDominica,
  IconDominicanRepublic,
  IconEastTimor,
  IconEcuador,
  IconEgypt,
  IconElSalvador,
  IconEquatorialGuinea,
  IconEritrea,
  IconEstonia,
  IconEswatini,
  IconEthiopia,
  IconFalklandIslands,
  IconFiji,
  IconFinland,
  IconFrance,
  IconFrenchGuiana,
  IconFrenchPolynesia,
  IconGabon,
  IconGambia,
  IconGeorgia,
  IconGermany,
  IconGhana,
  IconGreece,
  IconGrenada,
  IconGuatemala,
  IconGuinea,
  IconGuineaBissau,
  IconGuyana,
  IconHaiti,
  IconHonduras,
  IconHongKong,
  IconHungary,
  IconIceland,
  IconIndia,
  IconIndonesia,
  IconIran,
  IconIraq,
  IconIreland,
  IconIsrael,
  IconItaly,
  IconIvoryCoast,
  IconJamaica,
  IconJapan,
  IconJordan,
  IconKazakhstan,
  IconKenya,
  IconKiribati,
  IconKuwait,
  IconKyrgyzstan,
  IconLaos,
  IconLatvia,
  IconLebanon,
  IconLesotho,
  IconLiberia,
  IconLibya,
  IconLiechtenstein,
  IconLithuania,
  IconLuxembourg,
  IconMadagascar,
  IconMalawi,
  IconMalaysia,
  IconMaldives,
  IconMali,
  IconMalta,
  IconMarshallIslands,
  IconMauritania,
  IconMauritius,
  IconMexico,
  IconMicronesia,
  IconMoldova,
  IconMonaco,
  IconMongolia,
  IconMontenegro,
  IconMorocco,
  IconMozanbique,
  IconMyanmar,
  IconNamibia,
  IconNauru,
  IconNepal,
  IconNetherlands,
  IconNewCaledonia,
  IconNewZealand,
  IconNicaragua,
  IconNiger,
  IconNigeria,
  IconNorthKorea,
  IconNorthMacedonia,
  IconNorway,
  IconOman,
  IconPakistan,
  IconPalau,
  IconPalestine,
  IconPanama,
  IconPapuaNewGuinea,
  IconParaguay,
  IconPeru,
  IconPhilippines,
  IconPoland,
  IconPortugal,
  IconPuertoRico,
  IconQatar,
  IconRepublicCongo,
  IconRomania,
  IconRussia,
  IconRwanda,
  IconSaintKittsNevis,
  IconSaintLucia,
  IconSaintVincentGrenadines,
  IconSamoa,
  IconSanMarino,
  IconSaoTomePrincipe,
  IconSaudiArabia,
  IconSenegal,
  IconSerbia,
  IconSeychelles,
  IconSierraLeone,
  IconSingapore,
  IconSlovakia,
  IconSlovenia,
  IconSolomonIslands,
  IconSomalia,
  IconSouthAfrica,
  IconSouthKorea,
  IconSouthSudan,
  IconSpain,
  IconSriLanka,
  IconSudan,
  IconSuriname,
  IconSweden,
  IconSwitzerland,
  IconSyria,
  IconTaiwan,
  IconTajikistan,
  IconTanzania,
  IconThailand,
  IconTogo,
  IconTonga,
  IconTrinidadTobago,
  IconTunisia,
  IconTurkey,
  IconTurkmenistan,
  IconTuvalu,
  IconUganda,
  IconUkraine,
  IconUnitedArabEmirates,
  IconUnitedKingdom,
  IconUnitedStates,
  IconUruguay,
  IconUzbekistan,
  IconVanuatu,
  IconVaticanCity,
  IconVenezuela,
  IconVietnam,
  IconYemen,
  IconZambia,
  IconZimbabwe,
} from "nucleo-flags"

export type NucleoFlagComponent = FC<IconProps>

export const countryFlagIconByIso: Record<string, NucleoFlagComponent> = {
  AD: IconAndorra,
  AE: IconUnitedArabEmirates,
  AF: IconAfghanistan,
  AG: IconAntiguaBarbuda,
  AL: IconAlbania,
  AM: IconArmenia,
  AO: IconAngola,
  AR: IconArgentina,
  AT: IconAustria,
  AU: IconAustralia,
  AZ: IconAzerbaijan,
  BA: IconBosniaHerzegovina,
  BB: IconBarbados,
  BD: IconBangladesh,
  BE: IconBelgium,
  BF: IconBurkinaFaso,
  BG: IconBulgaria,
  BH: IconBahrain,
  BI: IconBurundi,
  BJ: IconBenin,
  BN: IconBrunei,
  BO: IconBolivia,
  BR: IconBrazil,
  BS: IconBahamas,
  BT: IconBhutan,
  BW: IconBotswana,
  BY: IconBelarus,
  BZ: IconBelize,
  CA: IconCanada,
  CD: IconDemocraticRepublicCongo,
  CF: IconCentralAfricanRepublic,
  CG: IconRepublicCongo,
  CH: IconSwitzerland,
  CI: IconIvoryCoast,
  CL: IconChile,
  CM: IconCameroon,
  CN: IconChina,
  CO: IconColombia,
  CR: IconCostaRica,
  CU: IconCuba,
  CV: IconCapeVerde,
  CY: IconCyprus,
  CZ: IconCzechia,
  DE: IconGermany,
  DJ: IconDjibouti,
  DK: IconDenmark,
  DM: IconDominica,
  DO: IconDominicanRepublic,
  DZ: IconAlgeria,
  EC: IconEcuador,
  EE: IconEstonia,
  EG: IconEgypt,
  ER: IconEritrea,
  ES: IconSpain,
  ET: IconEthiopia,
  FI: IconFinland,
  FJ: IconFiji,
  FK: IconFalklandIslands,
  FM: IconMicronesia,
  FR: IconFrance,
  GA: IconGabon,
  GB: IconUnitedKingdom,
  GD: IconGrenada,
  GE: IconGeorgia,
  GF: IconFrenchGuiana,
  GH: IconGhana,
  GM: IconGambia,
  GN: IconGuinea,
  GQ: IconEquatorialGuinea,
  GR: IconGreece,
  GT: IconGuatemala,
  GW: IconGuineaBissau,
  GY: IconGuyana,
  HK: IconHongKong,
  HN: IconHonduras,
  HR: IconCroatia,
  HT: IconHaiti,
  HU: IconHungary,
  ID: IconIndonesia,
  IE: IconIreland,
  IL: IconIsrael,
  IN: IconIndia,
  IQ: IconIraq,
  IR: IconIran,
  IS: IconIceland,
  IT: IconItaly,
  JM: IconJamaica,
  JO: IconJordan,
  JP: IconJapan,
  KE: IconKenya,
  KG: IconKyrgyzstan,
  KH: IconCambodia,
  KI: IconKiribati,
  KM: IconComoros,
  KN: IconSaintKittsNevis,
  KP: IconNorthKorea,
  KR: IconSouthKorea,
  KW: IconKuwait,
  KZ: IconKazakhstan,
  LA: IconLaos,
  LB: IconLebanon,
  LC: IconSaintLucia,
  LI: IconLiechtenstein,
  LK: IconSriLanka,
  LR: IconLiberia,
  LS: IconLesotho,
  LT: IconLithuania,
  LU: IconLuxembourg,
  LV: IconLatvia,
  LY: IconLibya,
  MA: IconMorocco,
  MC: IconMonaco,
  MD: IconMoldova,
  ME: IconMontenegro,
  MG: IconMadagascar,
  MH: IconMarshallIslands,
  MK: IconNorthMacedonia,
  ML: IconMali,
  MM: IconMyanmar,
  MN: IconMongolia,
  MR: IconMauritania,
  MT: IconMalta,
  MU: IconMauritius,
  MV: IconMaldives,
  MW: IconMalawi,
  MX: IconMexico,
  MY: IconMalaysia,
  MZ: IconMozanbique,
  NA: IconNamibia,
  NC: IconNewCaledonia,
  NE: IconNiger,
  NG: IconNigeria,
  NI: IconNicaragua,
  NL: IconNetherlands,
  NO: IconNorway,
  NP: IconNepal,
  NR: IconNauru,
  NZ: IconNewZealand,
  OM: IconOman,
  PA: IconPanama,
  PE: IconPeru,
  PF: IconFrenchPolynesia,
  PG: IconPapuaNewGuinea,
  PH: IconPhilippines,
  PK: IconPakistan,
  PL: IconPoland,
  PR: IconPuertoRico,
  PS: IconPalestine,
  PT: IconPortugal,
  PW: IconPalau,
  PY: IconParaguay,
  QA: IconQatar,
  RO: IconRomania,
  RS: IconSerbia,
  RU: IconRussia,
  RW: IconRwanda,
  SA: IconSaudiArabia,
  SB: IconSolomonIslands,
  SC: IconSeychelles,
  SD: IconSudan,
  SE: IconSweden,
  SG: IconSingapore,
  SI: IconSlovenia,
  SK: IconSlovakia,
  SL: IconSierraLeone,
  SM: IconSanMarino,
  SN: IconSenegal,
  SO: IconSomalia,
  SR: IconSuriname,
  SS: IconSouthSudan,
  ST: IconSaoTomePrincipe,
  SV: IconElSalvador,
  SY: IconSyria,
  SZ: IconEswatini,
  TD: IconChad,
  TG: IconTogo,
  TH: IconThailand,
  TJ: IconTajikistan,
  TL: IconEastTimor,
  TM: IconTurkmenistan,
  TN: IconTunisia,
  TO: IconTonga,
  TR: IconTurkey,
  TT: IconTrinidadTobago,
  TV: IconTuvalu,
  TW: IconTaiwan,
  TZ: IconTanzania,
  UA: IconUkraine,
  UG: IconUganda,
  US: IconUnitedStates,
  UY: IconUruguay,
  UZ: IconUzbekistan,
  VA: IconVaticanCity,
  VC: IconSaintVincentGrenadines,
  VE: IconVenezuela,
  VN: IconVietnam,
  VU: IconVanuatu,
  WS: IconSamoa,
  YE: IconYemen,
  ZA: IconSouthAfrica,
  ZM: IconZambia,
  ZW: IconZimbabwe,
}

