#!/usr/bin/env node
/**
 * Download flag PNGs from flagcdn.com, normalize to uniform 3:2 (country-flag-icons),
 * copy to business/public/flags, and regenerate manifests.
 */
import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'
import sharp from 'sharp'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const sharedRoot = path.resolve(__dirname, '..')
const assetsDir = path.join(sharedRoot, 'assets', 'flags')
const isoCodesOut = path.join(sharedRoot, 'src', 'flags', 'flag-iso-codes.ts')
const manifestOut = path.join(sharedRoot, 'src', 'flags', 'flag-assets.manifest.ts')
const webManifestOut = path.join(sharedRoot, 'src', 'flags', 'flag-assets.web.manifest.ts')
const businessFlagsDir = path.resolve(sharedRoot, '../../business/public/flags')

/** flagcdn width (w320 is sharp on retina). */
const FLAGCDN_WIDTH = Number.parseInt(process.env.FLAGCDN_WIDTH || '320', 10) || 320
/** Uniform 3:2 output — matches country-flag-icons / UI frames. */
const FLAG_OUT_WIDTH = FLAGCDN_WIDTH
const FLAG_OUT_HEIGHT = Math.round((FLAGCDN_WIDTH * 2) / 3)
/** EU flag is a circle of stars on blue — zoom so it matches visual weight of country flags. */
const FLAG_NORMALIZE_ZOOM = { EU: 1.22 }
const forceRedownload = process.argv.includes('--force')

function extractIsoCodes() {
  if (fs.existsSync(isoCodesOut)) {
    const src = fs.readFileSync(isoCodesOut, 'utf8')
    const codes = [...src.matchAll(/"([A-Z]{2})"/g)].map((m) => m[1])
    if (codes.length > 0) {
      if (!codes.includes('EU')) codes.push('EU')
      return [...new Set(codes)].sort()
    }
  }
  throw new Error('flag-iso-codes.ts missing or empty — restore from git or add ISO list')
}

async function downloadFlag(iso) {
  const lower = iso.toLowerCase()
  const url = `https://flagcdn.com/w${FLAGCDN_WIDTH}/${lower}.png`
  const res = await fetch(url)
  if (!res.ok) throw new Error(`${iso}: HTTP ${res.status}`)
  return Buffer.from(await res.arrayBuffer())
}

/** Fit flag into fixed 3:2 canvas so every asset fills UI frames consistently. */
async function normalizeFlagPng(input, iso) {
  const zoom = FLAG_NORMALIZE_ZOOM[iso] ?? 1
  let pipeline = sharp(input)
  if (zoom !== 1) {
    const zw = Math.round(FLAG_OUT_WIDTH * zoom)
    const zh = Math.round(FLAG_OUT_HEIGHT * zoom)
    pipeline = pipeline.resize(zw, zh, { fit: 'cover', position: 'centre' })
  }
  return pipeline
    .resize(FLAG_OUT_WIDTH, FLAG_OUT_HEIGHT, {
      fit: 'cover',
      position: 'centre',
    })
    .png({ compressionLevel: 9, adaptiveFiltering: true })
    .toBuffer()
}

async function writeNormalizedFlag(iso, rawBuf) {
  const dest = path.join(assetsDir, `${iso.toLowerCase()}.png`)
  const normalized = await normalizeFlagPng(rawBuf, iso)
  fs.writeFileSync(dest, normalized)
  return dest
}

function writeIsoCodesFile(codes) {
  const body = codes.map((c) => `  "${c}",`).join('\n')
  fs.writeFileSync(
    isoCodesOut,
    `/** @generated by packages/shared/scripts/sync-flags.mjs — do not edit */\nexport const FLAG_ISO_CODES = [\n${body}\n] as const\n\nexport type FlagIsoCode = (typeof FLAG_ISO_CODES)[number]\n\nexport const FLAG_ISO_SET = new Set<string>(FLAG_ISO_CODES)\n`
  )
}

function writeManifest(codes) {
  const entries = codes
    .map((iso) => `  ${iso}: require('../../assets/flags/${iso.toLowerCase()}.png'),`)
    .join('\n')
  fs.writeFileSync(
    manifestOut,
    `/** @generated by packages/shared/scripts/sync-flags.mjs — do not edit */\nexport const FLAG_ASSETS: Record<string, number> = {\n${entries}\n}\n`
  )
}

function writeWebManifest(codes) {
  const entries = codes
    .map((iso) => `  ${iso}: require('../../assets/flags/${iso.toLowerCase()}.png'),`)
    .join('\n')
  fs.writeFileSync(
    webManifestOut,
    `/** @generated by packages/shared/scripts/sync-flags.mjs — do not edit */
type FlagModule = string | { src?: string; default?: string | { src?: string } }

function resolveFlagModule(mod: FlagModule): string {
  if (typeof mod === 'string') return mod
  if (mod && typeof mod === 'object') {
    const d = mod.default
    if (typeof d === 'string') return d
    if (d && typeof d === 'object' && typeof d.src === 'string') return d.src
    if (typeof mod.src === 'string') return mod.src
  }
  return ''
}

const FLAG_MODULES: Record<string, FlagModule> = {
${entries}
}

/** Webpack/Next bundled flag URL (no /public round-trip). */
export function getFlagBundledSrc(iso: string): string | undefined {
  const mod = FLAG_MODULES[iso]
  if (!mod) return undefined
  const src = resolveFlagModule(mod)
  return src || undefined
}
`,
  )
}

function copyToBusiness(codes) {
  fs.mkdirSync(businessFlagsDir, { recursive: true })
  for (const iso of codes) {
    const lower = iso.toLowerCase()
    const src = path.join(assetsDir, `${lower}.png`)
    if (!fs.existsSync(src)) {
      console.warn(`Skip copy ${iso}: missing ${src}`)
      continue
    }
    const dest = path.join(businessFlagsDir, `${lower}.png`)
    fs.copyFileSync(src, dest)
  }
}

async function needsNormalize(iso) {
  const dest = path.join(assetsDir, `${iso.toLowerCase()}.png`)
  if (!fs.existsSync(dest) || fs.statSync(dest).size === 0) return true
  if (forceRedownload) return true
  try {
    const meta = await sharp(dest).metadata()
    if (meta.width !== FLAG_OUT_WIDTH || meta.height !== FLAG_OUT_HEIGHT) return true
  } catch {
    return true
  }
  return false
}

async function main() {
  const codes = extractIsoCodes()
  fs.mkdirSync(assetsDir, { recursive: true })
  console.log(
    `Syncing ${codes.length} flags → ${FLAG_OUT_WIDTH}×${FLAG_OUT_HEIGHT} (3:2)${forceRedownload ? ' (force)' : ''}…`
  )
  let ok = 0
  for (const iso of codes) {
    try {
      if (await needsNormalize(iso)) {
        const raw = await downloadFlag(iso)
        await writeNormalizedFlag(iso, raw)
        process.stdout.write('.')
      } else {
        process.stdout.write('-')
      }
      ok++
    } catch (e) {
      console.error(`\nFailed ${iso}:`, e.message)
    }
  }
  console.log(`\n${ok}/${codes.length} flags in ${assetsDir}`)
  writeIsoCodesFile(codes)
  writeManifest(codes)
  writeWebManifest(codes)
  copyToBusiness(codes)
  console.log('Copied to', businessFlagsDir)
  console.log('Wrote', isoCodesOut, manifestOut, webManifestOut)
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})
