#!/usr/bin/env node
/**
 * Download flag PNGs from flagcdn.com into packages/shared/assets/flags,
 * copy to business/public/flags, and regenerate Metro manifest + ISO list.
 */
import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const sharedRoot = path.resolve(__dirname, '..')
const assetsDir = path.join(sharedRoot, 'assets', 'flags')
const isoCodesOut = path.join(sharedRoot, 'src', 'flags', 'flag-iso-codes.ts')
const manifestOut = path.join(sharedRoot, 'src', 'flags', 'flag-assets.manifest.ts')
const webManifestOut = path.join(sharedRoot, 'src', 'flags', 'flag-assets.web.manifest.ts')
const businessFlagsDir = path.resolve(sharedRoot, '../../business/public/flags')

/** flagcdn width (w80 was soft on retina; w320 is sharp up to ~80px display width). */
const FLAGCDN_WIDTH = Number.parseInt(process.env.FLAGCDN_WIDTH || '320', 10) || 320
const forceRedownload = process.argv.includes('--force')

function extractIsoCodes() {
  if (fs.existsSync(isoCodesOut)) {
    const src = fs.readFileSync(isoCodesOut, 'utf8')
    const codes = [...src.matchAll(/"([A-Z]{2})"/g)].map((m) => m[1])
    if (codes.length > 0) {
      if (!codes.includes('EU')) codes.push('EU')
      return [...new Set(codes)].sort()
    }
  }
  throw new Error('flag-iso-codes.ts missing or empty — restore from git or add ISO list')
}

async function downloadFlag(iso) {
  const lower = iso.toLowerCase()
  const url = `https://flagcdn.com/w${FLAGCDN_WIDTH}/${lower}.png`
  const dest = path.join(assetsDir, `${lower}.png`)
  const res = await fetch(url)
  if (!res.ok) throw new Error(`${iso}: HTTP ${res.status}`)
  const buf = Buffer.from(await res.arrayBuffer())
  fs.writeFileSync(dest, buf)
  return dest
}

function writeIsoCodesFile(codes) {
  const body = codes.map((c) => `  "${c}",`).join('\n')
  fs.writeFileSync(
    isoCodesOut,
    `/** @generated by packages/shared/scripts/sync-flags.mjs — do not edit */\nexport const FLAG_ISO_CODES = [\n${body}\n] as const\n\nexport type FlagIsoCode = (typeof FLAG_ISO_CODES)[number]\n\nexport const FLAG_ISO_SET = new Set<string>(FLAG_ISO_CODES)\n`
  )
}

function writeManifest(codes) {
  const entries = codes
    .map((iso) => `  ${iso}: require('../../assets/flags/${iso.toLowerCase()}.png'),`)
    .join('\n')
  fs.writeFileSync(
    manifestOut,
    `/** @generated by packages/shared/scripts/sync-flags.mjs — do not edit */\nexport const FLAG_ASSETS: Record<string, number> = {\n${entries}\n}\n`
  )
}

function writeWebManifest(codes) {
  const entries = codes
    .map((iso) => `  ${iso}: require('../../assets/flags/${iso.toLowerCase()}.png'),`)
    .join('\n')
  fs.writeFileSync(
    webManifestOut,
    `/** @generated by packages/shared/scripts/sync-flags.mjs — do not edit */
type FlagModule = string | { src?: string; default?: string | { src?: string } }

function resolveFlagModule(mod: FlagModule): string {
  if (typeof mod === 'string') return mod
  if (mod && typeof mod === 'object') {
    const d = mod.default
    if (typeof d === 'string') return d
    if (d && typeof d === 'object' && typeof d.src === 'string') return d.src
    if (typeof mod.src === 'string') return mod.src
  }
  return ''
}

const FLAG_MODULES: Record<string, FlagModule> = {
${entries}
}

/** Webpack/Next bundled flag URL (no /public round-trip). */
export function getFlagBundledSrc(iso: string): string | undefined {
  const mod = FLAG_MODULES[iso]
  if (!mod) return undefined
  const src = resolveFlagModule(mod)
  return src || undefined
}
`,
  )
}

function copyToBusiness(codes) {
  fs.mkdirSync(businessFlagsDir, { recursive: true })
  for (const iso of codes) {
    const lower = iso.toLowerCase()
    const src = path.join(assetsDir, `${lower}.png`)
    if (!fs.existsSync(src)) {
      console.warn(`Skip copy ${iso}: missing ${src}`)
      continue
    }
    const dest = path.join(businessFlagsDir, `${lower}.png`)
    fs.copyFileSync(src, dest)
  }
}

async function main() {
  const codes = extractIsoCodes()
  fs.mkdirSync(assetsDir, { recursive: true })
  console.log(`Syncing ${codes.length} flags at w${FLAGCDN_WIDTH}${forceRedownload ? ' (force)' : ''}…`)
  let ok = 0
  for (const iso of codes) {
    const dest = path.join(assetsDir, `${iso.toLowerCase()}.png`)
    if (!forceRedownload && fs.existsSync(dest) && fs.statSync(dest).size > 0) {
      ok++
      continue
    }
    try {
      await downloadFlag(iso)
      ok++
      process.stdout.write('.')
    } catch (e) {
      console.error(`\nFailed ${iso}:`, e.message)
    }
  }
  console.log(`\n${ok}/${codes.length} flags in ${assetsDir}`)
  writeIsoCodesFile(codes)
  writeManifest(codes)
  writeWebManifest(codes)
  copyToBusiness(codes)
  console.log('Copied to', businessFlagsDir)
  console.log('Wrote', isoCodesOut, manifestOut, webManifestOut)
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})
