#!/usr/bin/env node
/**
 * Download flag PNGs from flagcdn.com, normalize to uniform 3:2 (country-flag-icons),
 * copy to business/public/flags and office/public/flags, and regenerate manifests.
 */
import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'
import sharp from 'sharp'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const sharedRoot = path.resolve(__dirname, '..')
const assetsDir = path.join(sharedRoot, 'assets', 'flags')
const isoCodesOut = path.join(sharedRoot, 'src', 'flags', 'flag-iso-codes.ts')
const manifestOut = path.join(sharedRoot, 'src', 'flags', 'flag-assets.manifest.ts')
const webManifestOut = path.join(sharedRoot, 'src', 'flags', 'flag-assets.web.manifest.ts')
const businessFlagsDir = path.resolve(sharedRoot, '../../business/public/flags')
const officeFlagsDir = path.resolve(sharedRoot, '../../office/public/flags')

/** flagcdn width (w320 is sharp on retina). */
const FLAGCDN_WIDTH = Number.parseInt(process.env.FLAGCDN_WIDTH || '320', 10) || 320
/** Uniform 3:2 output — matches country-flag-icons / UI frames. */
const FLAG_OUT_WIDTH = FLAGCDN_WIDTH
const FLAG_OUT_HEIGHT = Math.round((FLAGCDN_WIDTH * 2) / 3)
const TARGET_ASPECT = FLAG_OUT_WIDTH / FLAG_OUT_HEIGHT
/** Bump when normalize logic changes — triggers re-download of all flags. */
const NORMALIZE_VERSION = 2
const normalizeVersionFile = path.join(assetsDir, '.normalize-version')
const forceRedownload = process.argv.includes('--force')

function extractIsoCodes() {
  if (fs.existsSync(isoCodesOut)) {
    const src = fs.readFileSync(isoCodesOut, 'utf8')
    const codes = [...src.matchAll(/"([A-Z]{2})"/g)].map((m) => m[1])
    if (codes.length > 0) {
      if (!codes.includes('EU')) codes.push('EU')
      return [...new Set(codes)].sort()
    }
  }
  throw new Error('flag-iso-codes.ts missing or empty — restore from git or add ISO list')
}

async function downloadFlag(iso) {
  const lower = iso.toLowerCase()
  const url = `https://flagcdn.com/w${FLAGCDN_WIDTH}/${lower}.png`
  const res = await fetch(url)
  if (!res.ok) throw new Error(`${iso}: HTTP ${res.status}`)
  return Buffer.from(await res.arrayBuffer())
}

/** Sample top-left pixel for letterbox background (square/tall flags). */
async function sampleCornerBackground(input) {
  const { data, info } = await sharp(input)
    .extract({ left: 0, top: 0, width: 1, height: 1 })
    .ensureAlpha()
    .raw()
    .toBuffer({ resolveWithObject: true })
  const ch = info.channels
  return {
    r: data[0],
    g: data[1],
    b: data[2],
    alpha: ch >= 4 ? data[3] / 255 : 1,
  }
}

/**
 * Fit flag into fixed 3:2 canvas.
 * - ~3:2 and wider sources: cover (fills frame, e.g. US).
 * - Square/taller sources: contain + corner background (avoids cropping EU stars, CH cross).
 */
async function normalizeFlagPng(input) {
  const meta = await sharp(input).metadata()
  const srcW = meta.width || FLAG_OUT_WIDTH
  const srcH = meta.height || FLAG_OUT_HEIGHT
  const srcAspect = srcW / srcH
  const nearTarget = Math.abs(srcAspect - TARGET_ASPECT) < 0.06
  const fit = nearTarget || srcAspect > TARGET_ASPECT ? 'cover' : 'contain'

  let pipeline = sharp(input)
  if (fit === 'contain') {
    const background = await sampleCornerBackground(input)
    pipeline = pipeline.resize(FLAG_OUT_WIDTH, FLAG_OUT_HEIGHT, {
      fit: 'contain',
      position: 'centre',
      background,
    })
  } else {
    pipeline = pipeline.resize(FLAG_OUT_WIDTH, FLAG_OUT_HEIGHT, {
      fit: 'cover',
      position: 'centre',
    })
  }

  return pipeline.png({ compressionLevel: 9, adaptiveFiltering: true }).toBuffer()
}

async function writeNormalizedFlag(iso, rawBuf) {
  const dest = path.join(assetsDir, `${iso.toLowerCase()}.png`)
  const normalized = await normalizeFlagPng(rawBuf)
  fs.writeFileSync(dest, normalized)
  return dest
}

function writeIsoCodesFile(codes) {
  const body = codes.map((c) => `  "${c}",`).join('\n')
  fs.writeFileSync(
    isoCodesOut,
    `/** @generated by packages/shared/scripts/sync-flags.mjs — do not edit */\nexport const FLAG_ISO_CODES = [\n${body}\n] as const\n\nexport type FlagIsoCode = (typeof FLAG_ISO_CODES)[number]\n\nexport const FLAG_ISO_SET = new Set<string>(FLAG_ISO_CODES)\n`
  )
}

function writeManifest(codes) {
  const entries = codes
    .map((iso) => `  ${iso}: require('../../assets/flags/${iso.toLowerCase()}.png'),`)
    .join('\n')
  fs.writeFileSync(
    manifestOut,
    `/** @generated by packages/shared/scripts/sync-flags.mjs — do not edit */\nexport const FLAG_ASSETS: Record<string, number> = {\n${entries}\n}\n`
  )
}

function writeWebManifest() {
  fs.writeFileSync(
    webManifestOut,
    `/** @generated by packages/shared/scripts/sync-flags.mjs — do not edit */

/**
 * Web flags are served from \`/public/flags/{iso}.png\` (see \`getFlagPublicUrl\`),
 * cached immutably via next.config headers. We intentionally do NOT \`require()\` the
 * bundled PNGs here: Turbopack (local dev) emits those as runtime requires in the SSR
 * chunk and crashes with "Cannot find module '../../assets/flags/xx.png'". Returning
 * undefined lets \`CountryFlag\` fall back to the public URL, which works in both
 * Turbopack (dev) and webpack (prod) builds.
 */
export function getFlagBundledSrc(_iso: string): string | undefined {
  return undefined
}
`,
  )
}

function copyToPublicApps(codes) {
  for (const destDir of [businessFlagsDir, officeFlagsDir]) {
    fs.mkdirSync(destDir, { recursive: true })
    for (const iso of codes) {
      const lower = iso.toLowerCase()
      const src = path.join(assetsDir, `${lower}.png`)
      if (!fs.existsSync(src)) {
        console.warn(`Skip copy ${iso}: missing ${src}`)
        continue
      }
      const dest = path.join(destDir, `${lower}.png`)
      fs.copyFileSync(src, dest)
    }
  }
}

function normalizeVersionStale() {
  if (forceRedownload) return true
  if (!fs.existsSync(normalizeVersionFile)) return true
  return fs.readFileSync(normalizeVersionFile, 'utf8').trim() !== String(NORMALIZE_VERSION)
}

async function needsNormalize(iso) {
  const dest = path.join(assetsDir, `${iso.toLowerCase()}.png`)
  if (!fs.existsSync(dest) || fs.statSync(dest).size === 0) return true
  if (normalizeVersionStale()) return true
  try {
    const meta = await sharp(dest).metadata()
    if (meta.width !== FLAG_OUT_WIDTH || meta.height !== FLAG_OUT_HEIGHT) return true
  } catch {
    return true
  }
  return false
}

async function main() {
  const codes = extractIsoCodes()
  fs.mkdirSync(assetsDir, { recursive: true })
  console.log(
    `Syncing ${codes.length} flags → ${FLAG_OUT_WIDTH}×${FLAG_OUT_HEIGHT} (3:2)${forceRedownload ? ' (force)' : ''}…`
  )
  let ok = 0
  for (const iso of codes) {
    try {
      if (await needsNormalize(iso)) {
        const raw = await downloadFlag(iso)
        await writeNormalizedFlag(iso, raw)
        process.stdout.write('.')
      } else {
        process.stdout.write('-')
      }
      ok++
    } catch (e) {
      console.error(`\nFailed ${iso}:`, e.message)
    }
  }
  console.log(`\n${ok}/${codes.length} flags in ${assetsDir}`)
  if (ok > 0) {
    fs.writeFileSync(normalizeVersionFile, `${NORMALIZE_VERSION}\n`)
  }
  writeIsoCodesFile(codes)
  writeManifest(codes)
  writeWebManifest()
  copyToPublicApps(codes)
  console.log('Copied to', businessFlagsDir, 'and', officeFlagsDir)
  console.log('Wrote', isoCodesOut, manifestOut, webManifestOut)
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})
