// Bridge KYC helper functions for mobile app

/**
 * Check if country is USA
 */
export function isUSACountry(countryCode: string): boolean {
  return countryCode?.toUpperCase() === 'US' || countryCode?.toUpperCase() === 'USA'
}

/**
 * Check if country is in EEA (European Economic Area)
 */
export function isEEACountry(countryCode: string): boolean {
  const eeaCountries = [
    'AT', 'BE', 'BG', 'HR', 'CY', 'CZ', 'DK', 'EE', 'FI', 'FR', 'DE', 'GR',
    'HU', 'IE', 'IT', 'LV', 'LT', 'LU', 'MT', 'NL', 'PL', 'PT', 'RO', 'SK',
    'SI', 'ES', 'SE', 'IS', 'LI', 'NO',
  ]
  return eeaCountries.includes(countryCode?.toUpperCase())
}

/**
 * Get which Bridge fields are required based on country
 */
export function getBridgeRequiredFields(countryCode: string): {
  us: boolean
  eea: boolean
  international: boolean
} {
  const us = isUSACountry(countryCode)
  const eea = isEEACountry(countryCode)
  const international = !us && !eea
  
  return { us, eea, international }
}

/**
 * Format employment status for Bridge API
 * Maps UI values to Bridge expected values
 */
export function formatEmploymentStatus(value: string): string {
  const mapping: Record<string, string> = {
    'employed': 'employed',
    'unemployed': 'unemployed',
    'self_employed': 'self_employed',
    'retired': 'retired',
    'student': 'student',
  }
  return mapping[value] || value
}

/**
 * Format expected monthly flows for Bridge API
 * Maps UI ranges to Bridge format
 */
export function formatExpectedMonthly(value: string): string {
  const mapping: Record<string, string> = {
    '0_999': '0_999',
    '1000_4999': '1000_4999',
    '5000_9999': '5000_9999',
    '10000_plus': '10000_plus',
  }
  return mapping[value] || value
}

/**
 * Format account purpose for Bridge API
 */
export function formatAccountPurpose(value: string): string {
  const mapping: Record<string, string> = {
    'purchase_goods_and_services': 'purchase_goods_and_services',
    'receive_payments': 'receive_payments',
    'send_payments': 'send_payments',
    'savings': 'savings',
    'investment': 'investment',
    'other': 'other',
  }
  return mapping[value] || value
}

/**
 * Format source of funds for Bridge API
 * Maps legacy values to valid Bridge values
 */
export function formatSourceOfFunds(value: string): string {
  const mapping: Record<string, string> = {
    'salary': 'salary',
    'business_income': 'company_funds', // business_income is not valid, map to company_funds
    'investments': 'investments_loans',
    'inheritance': 'inheritance',
    'gift': 'gifts',
    'gifts': 'gifts',
    'savings': 'savings',
    'other': 'savings', // Default to savings for other
  }
  return mapping[value.toLowerCase()] || value
}

/**
 * Employment status options for dropdown
 * These are the valid Bridge values
 */
export const EMPLOYMENT_STATUS_OPTIONS = [
  { label: 'Employed', value: 'employed' },
  { label: 'Unemployed', value: 'unemployed' },
  { label: 'Self-Employed', value: 'self_employed' },
  { label: 'Retired', value: 'retired' },
  { label: 'Student', value: 'student' },
]

/**
 * Expected monthly flow ranges for dropdown
 */
export const EXPECTED_MONTHLY_OPTIONS = [
  { label: '$0 - $999', value: '0_999' },
  { label: '$1,000 - $4,999', value: '1000_4999' },
  { label: '$5,000 - $9,999', value: '5000_9999' },
  { label: '$10,000+', value: '10000_plus' },
]

/**
 * Account purpose options for dropdown
 * Must match Bridge's allowed values exactly:
 * business_transactions, charitable_donations, ecommerce_retail_payments,
 * investment_purposes, operating_a_company, other,
 * payments_to_friends_or_family_abroad, personal_or_living_expenses,
 * protect_wealth, purchase_goods_and_services,
 * receive_payment_for_freelancing, receive_salary
 */
export const ACCOUNT_PURPOSE_OPTIONS = [
  { label: 'Personal or Living Expenses', value: 'personal_or_living_expenses' },
  { label: 'Purchase Goods and Services', value: 'purchase_goods_and_services' },
  { label: 'Receive Payment for Freelancing', value: 'receive_payment_for_freelancing' },
  { label: 'Receive Salary', value: 'receive_salary' },
  { label: 'Payments to Friends or Family Abroad', value: 'payments_to_friends_or_family_abroad' },
  { label: 'Business Transactions', value: 'business_transactions' },
  { label: 'Operating a Company', value: 'operating_a_company' },
  { label: 'Investment Purposes', value: 'investment_purposes' },
  { label: 'Protect Wealth', value: 'protect_wealth' },
  { label: 'Ecommerce/Retail Payments', value: 'ecommerce_retail_payments' },
  { label: 'Charitable Donations', value: 'charitable_donations' },
  { label: 'Other', value: 'other' },
]

/**
 * Source of funds options for dropdown
 * Must match Bridge's allowed values: company_funds, ecommerce_reseller, gambling_proceeds,
 * gifts, government_benefits, inheritance, investments_loans, pension_retirement, salary,
 * sale_of_assets_real_estate, savings, someone_elses_funds
 * NOTE: business_income is NOT valid - use company_funds instead
 */
export const SOURCE_OF_FUNDS_OPTIONS = [
  { label: 'Salary', value: 'salary' },
  { label: 'Company Funds', value: 'company_funds' },
  { label: 'Ecommerce Reseller', value: 'ecommerce_reseller' },
  { label: 'Gambling Proceeds', value: 'gambling_proceeds' },
  { label: 'Gifts', value: 'gifts' },
  { label: 'Government Benefits', value: 'government_benefits' },
  { label: 'Inheritance', value: 'inheritance' },
  { label: 'Investments/Loans', value: 'investments_loans' },
  { label: 'Pension/Retirement', value: 'pension_retirement' },
  { label: 'Sale of Assets/Real Estate', value: 'sale_of_assets_real_estate' },
  { label: 'Savings', value: 'savings' },
  { label: 'Someone Else\'s Funds', value: 'someone_elses_funds' },
]

/**
 * Get all KYC options (no API calls needed - all static)
 * Returns occupation codes, source of funds, and employment status options
 * Occupation codes are fetched from Bridge API via script and stored statically
 */
export function getKycOptions(): {
  occupationCodes: Array<{ label: string; value: string }>
  sourceOfFunds: Array<{ label: string; value: string }>
  employmentStatus: Array<{ label: string; value: string }>
} {
  // All options are static - no API calls needed
  return {
    occupationCodes: OCCUPATION_OPTIONS,
    sourceOfFunds: SOURCE_OF_FUNDS_OPTIONS,
    employmentStatus: EMPLOYMENT_STATUS_OPTIONS,
  }
}

/**
 * Occupation options for dropdown
 * These are ALL occupation codes from Bridge API - GET /v0/lists/occupation_codes
 * Value is the occupation code (e.g., "132011" for "Accountant and auditor")
 * Last updated: 2025-12-03T16:30:09.624Z
 * Total codes: 569
 * Run: npx tsx scripts/fetch-occupation-codes.ts to update this list
 */
export const OCCUPATION_OPTIONS: Array<{ label: string; value: string }> = [
  { label: 'Accountant and auditor', value: '132011' },
  { label: 'Actor', value: '272011' },
  { label: 'Actuary', value: '152011' },
  { label: 'Acupuncturist', value: '291291' },
  { label: 'Adhesive bonding machine operator and tender', value: '519191' },
  { label: 'Administrative services manager', value: '113012' },
  { label: 'Advertising and promotions manager', value: '112011' },
  { label: 'Advertising sales agent', value: '413011' },
  { label: 'Aerospace engineer', value: '172011' },
  { label: 'Agent and business manager of artists performers and athletes', value: '131011' },
  { label: 'Agricultural and food science technician', value: '194010' },
  { label: 'Agricultural and food scientist', value: '191010' },
  { label: 'Agricultural engineer', value: '172021' },
  { label: 'Agricultural inspector', value: '452011' },
  { label: 'Aircraft mechanic and service technician', value: '493011' },
  { label: 'Aircraft pilots and flight engineer', value: '532010' },
  { label: 'Aircraft structure surfaces rigging and systems assembler', value: '512011' },
  { label: 'Air traffic controller and airfield operations specialist', value: '532020' },
  { label: 'Ambulance driver and attendant except emergency medical technician', value: '533011' },
  { label: 'Animal breeder', value: '452021' },
  { label: 'Animal caretaker', value: '392021' },
  { label: 'Animal control worker', value: '339011' },
  { label: 'Animal trainer', value: '392011' },
  { label: 'Architect except landscape and naval', value: '171011' },
  { label: 'Architectural and civil drafter', value: '173011' },
  { label: 'Architectural and engineering manager', value: '119041' },
  { label: 'Archivist curator and museum technician', value: '254010' },
  { label: 'Artist and related worker', value: '271010' },
  { label: 'Astronomer and physicist', value: '192010' },
  { label: 'Athletes and sports competitor', value: '272021' },
  { label: 'Atmospheric and space scientist', value: '192021' },
  { label: 'Audiologist', value: '291181' },
  { label: 'Audiovisual equipment installer and repairer', value: '492097' },
  { label: 'Automotive body and related repairer', value: '493021' },
  { label: 'Automotive glass installer and repairer', value: '493022' },
  { label: 'Automotive service technician and mechanic', value: '493023' },
  { label: 'Avionics technician', value: '492091' },
  { label: 'Baggage porter bellhop and concierge', value: '396010' },
  { label: 'Bailiff', value: '333011' },
  { label: 'Baker', value: '513011' },
  { label: 'Barber', value: '395011' },
  { label: 'Bartender', value: '353011' },
  { label: 'Bicycle repairer', value: '433011' },
  { label: 'Billing and posting clerk', value: '433021' },
  { label: 'Billing cost and rate clerk', value: '433031' },
  { label: 'Biochemist and biophysicist', value: '191020' },
  { label: 'Biological technician', value: '194021' },
  { label: 'Biomedical engineer', value: '172031' },
  { label: 'Boilermaker', value: '472011' },
  { label: 'Bookkeeping accounting and auditing clerk', value: '432020' },
  { label: 'Brazer', value: '472020' },
  { label: 'Brickmason and blockmason', value: '273011' },
  { label: 'Bridge and lock tender', value: '274010' },
  { label: 'Broadcast announcer and radio disc jockey', value: '434011' },
  { label: 'Brokerage clerk', value: '132031' },
  { label: 'Budget analyst', value: '493031' },
  { label: 'Bus and truck mechanic and diesel engine specialist', value: '131199' },
  { label: 'Bus driver transit and intercity', value: '513020' },
  { label: 'Business operations specialist', value: '131021' },
  { label: 'Butcher and meat cutter', value: '517011' },
  { label: 'Buyer and purchasing agent', value: '292031' },
  { label: 'Cabinetmaker and bench carpenter', value: '435011' },
  { label: 'Camera and photographic equipment repairer', value: '472031' },
  { label: 'Camera operator television video and motion picture', value: '472040' },
  { label: 'Cardiovascular technologist and technician', value: '412010' },
  { label: 'Cargo and freight agent', value: '472050' },
  { label: 'Carpenter', value: '351011' },
  { label: 'Carpet installer', value: '172041' },
  { label: 'Cartographer and photogrammetrist', value: '519010' },
  { label: 'Cashier', value: '194031' },
  { label: 'Cement mason and concrete finisher', value: '192030' },
  { label: 'Chef and head cook', value: '111011' },
  { label: 'Chemical engineer', value: '399011' },
  { label: 'Chemical plant and system operator', value: '211021' },
  { label: 'Chemist', value: '291011' },
  { label: 'Child social worker', value: '172051' },
  { label: 'Chiropractor', value: '131030' },
  { label: 'Choreographer', value: '537061' },
  { label: 'Civil engineer', value: '212011' },
  { label: 'Claims adjuster examiner investigator and adjuster', value: '193033' },
  { label: 'Cleaner of vehicles and equipment', value: '292010' },
  { label: 'Clinical laboratory technologist and technician', value: '272022' },
  { label: 'Coaches and scout', value: '499091' },
  { label: 'Coating painting and spraying machine setter operator and tender', value: '499092' },
  { label: 'Coin vending and amusement machine servicer and repairer', value: '432099' },
  { label: 'Commercial and industrial designer', value: '113111' },
  { label: 'Commercial diver', value: '131141' },
  { label: 'Commercial pilot', value: '131041' },
  { label: 'Compensation benefits and job analysis specialist', value: '151221' },
  { label: 'Compensation manager', value: '113021' },
  { label: 'Compliance officer', value: '492011' },
  { label: 'Computer and information research scientist', value: '172061' },
  { label: 'Computer and information systems manager', value: '151241' },
  { label: 'Computer hardware engineer', value: '519160' },
  { label: 'Computer network architect', value: '151299' },
  { label: 'Computer network support specialist', value: '151251' },
  { label: 'Computer programmer', value: '151230' },
  { label: 'Computer systems analyst', value: '151211' },
  { label: 'Computer user support specialist', value: '191030' },
  { label: 'Concierge', value: '474011' },
  { label: 'Conservation scientist and forester', value: '472070' },
  { label: 'Construction and building inspector', value: '472061' },
  { label: 'Construction equipment operator', value: '119021' },
  { label: 'Construction laborer', value: '499010' },
  { label: 'Construction manager', value: '5370XX' },
  { label: 'Control and valve installer and repairer', value: '352010' },
  { label: 'Conveyor dredge and hoist and winch operator', value: '333012' },
  { label: 'Cook', value: '434021' },
  { label: 'Correctional officer and jailer', value: '131051' },
  { label: 'Correspondence clerk', value: '211019' },
  { label: 'Cost estimator', value: '412021' },
  { label: 'Counselor other', value: '435021' },
  { label: 'Counter and rental clerk', value: '434031' },
  { label: 'Courier and messenger', value: '273092' },
  { label: 'Court municipal and license clerk', value: '537021' },
  { label: 'Court reporter and simultaneous captioner', value: '132041' },
  { label: 'Crane and tower operator', value: '434041' },
  { label: 'Credit analyst', value: '434051' },
  { label: 'Credit authorizer checker and clerk', value: '132070' },
  { label: 'Credit counselor and loan officer', value: '339091' },
  { label: 'Crossing guard and flagger', value: '519020' },
  { label: 'Crushing grinding polishing mixing and blending worker', value: '434051' },
  { label: 'Customer service representative', value: '514031' },
  { label: 'Cutting punching and press machine setter operator and tender metal and plastic', value: '519030' },
  { label: 'Cutting worker', value: '519080' },
  { label: 'Dancer', value: '319091' },
  { label: 'Data entry keyer', value: '291292' },
  { label: 'Database administrator', value: '291020' },
  { label: 'Dental assistant', value: '475010' },
  { label: 'Dental hygienist', value: '439031' },
  { label: 'Dental laboratory technician', value: '333021' },
  { label: 'Dentist', value: '292032' },
  { label: 'Derrick operator oil and gas', value: '29205X' },
  { label: 'Desktop publisher', value: '291031' },
  { label: 'Detective and criminal investigator', value: '359011' },
  { label: 'Diagnostic medical sonographer', value: '212021' },
  { label: 'Dietetic technician', value: '272091' },
  { label: 'Dietitian and nutritionist', value: '359021' },
  { label: 'Dining room and cafeteria attendant and bartender helper', value: '435032' },
  { label: 'Director religious activities and education', value: '419091' },
  { label: 'Dishwasher', value: '533030' },
  { label: 'Dispatcher', value: '472080' },
  { label: 'Door-to-door sales worker news and street vendor and related worker', value: '475023' },
  { label: 'Drafters', value: '193011' },
  { label: 'Dredge operator', value: '273041' },
  { label: 'Drilling and boring machine tool setter operator and tender metal and plastic', value: '211012' },
  { label: 'Driver sales worker', value: '119030' },
  { label: 'Drywall installer and taper', value: '173023' },
  { label: 'Earth driller', value: '172070' },
  { label: 'Economist', value: '492093' },
  { label: 'Editor', value: '49209X' },
  { label: 'Education administrator', value: '512020' },
  { label: 'Education and childcare administrator', value: '499051' },
  { label: 'Education teacher and instructor', value: '472111' },
  { label: 'Educational instruction and library worker', value: '492092' },
  { label: 'Electric motor power tool and related repairer', value: '492096' },
  { label: 'Electrical and electronic equipment assembler', value: '252020' },
  { label: 'Electrical and electronics drafter', value: '474021' },
  { label: 'Electrical and electronics engineering technologist and technician', value: '434061' },
  { label: 'Electrical engineer', value: '3940XX' },
  { label: 'Electrical power-line installer and repairer', value: '119161' },
  { label: 'Electrician', value: '292042' },
  { label: 'Electro-mechanical and mechatronics technologist and technician', value: '291214' },
  { label: 'Electronic equipment installer and repairer', value: '512031' },
  { label: 'Elementary middle and secondary school education administrator', value: '172199' },
  { label: 'Elevator and escalator installer and repairer', value: '272099' },
  { label: 'Embalmer', value: '119070' },
  { label: 'Emergency management director', value: '172081' },
  { label: 'Emergency medical technician and paramedic', value: '194040' },
  { label: 'Engine and other machine assembler', value: '192041' },
  { label: 'Engineering manager', value: '519194' },
  { label: 'Engineering teacher', value: '475022' },
  { label: 'Engineer', value: '436011' },
  { label: 'Entertainment attendant and related worker', value: '291128' },
  { label: 'Environmental engineer', value: '399031' },
  { label: 'Environmental science and protection technician including health', value: '475032' },
  { label: 'Environmental scientist and specialist including health', value: '519041' },
  { label: 'Epidemiologist', value: '113013' },
  { label: 'Etcher and engraver', value: '119013' },
  { label: 'Excavating and loading machine and dragline operator', value: '271022' },
  { label: 'Executive secretary and executive administrative assistant', value: '353023' },
  { label: 'Exercise physiologist', value: '474031' },
  { label: 'Explosives worker ordnance handling expert and blaster', value: '434071' },
  { label: 'Extraction worker', value: '132051' },
  { label: 'Extruding and drawing machine setter operator and tender metal and plastic', value: '433099' },
  { label: 'Fabric and apparel patternmaker', value: '132061' },
  { label: 'Fabric mender', value: '113031' },
  { label: 'Family and general practitioner', value: '332011' },
  { label: 'Farm equipment mechanic and service technician', value: '332020' },
  { label: 'Farmer rancher and other agricultural manager', value: '552010' },
  { label: 'Fashion designer', value: '471011' },
  { label: 'Fast food and counter worker', value: '331011' },
  { label: 'Fence erector', value: '451011' },
  { label: 'Fiberglass laminator and fabricator', value: '331021' },
  { label: 'File clerk', value: '351012' },
  { label: 'Film and video editor', value: '371011' },
  { label: 'Financial advisor', value: '371012' },
  { label: 'Financial analyst', value: '491011' },
  { label: 'Financial examiner', value: '411012' },
  { label: 'Financial manager', value: '431011' },
  { label: 'Financial quantitative analyst', value: '331012' },
  { label: 'Fine artist including painter sculptor and illustrator', value: '511011' },
  { label: 'Fire inspector', value: '331099' },
  { label: 'Firefighter', value: '411011' },
  { label: 'First-line supervisor of construction trades and extraction workers', value: '331091' },
  { label: 'First-line supervisor of correctional officers', value: '333031' },
  { label: 'First-line supervisor of firefighting and prevention workers', value: '453031' },
  { label: 'First-line supervisor of food preparation and serving workers', value: '532031' },
  { label: 'First-line supervisor of helpers laborers and material movers', value: '271023' },
  { label: 'First-line supervisor of housekeeping and janitorial workers', value: '513091' },
  { label: 'First-line supervisor of landscaping lawn service and groundskeeping workers', value: '513092' },
  { label: 'First-line supervisor of mechanics installers and repairers', value: '513093' },
  { label: 'First-line supervisor of office and administrative support workers', value: '359099' },
  { label: 'First-line supervisor of personal service workers', value: '352021' },
  { label: 'First-line supervisor of police and detectives', value: '513099' },
  { label: 'First-line supervisor of production and operating workers', value: '353041' },
  { label: 'First-line supervisor of protective service workers', value: '119051' },
  { label: 'First-line supervisor of retail sales workers', value: '454011' },
  { label: 'First-line supervisor of transportation and material-moving workers', value: '514020' },
  { label: 'Fish and game warden', value: '131131' },
  { label: 'Fitness trainer and aerobics instructor', value: '119171' },
  { label: 'Flight attendant', value: '519051' },
  { label: 'Floor finisher', value: '517021' },
  { label: 'Floor layer', value: '433041' },
  { label: 'Floral designer', value: '393010' },
  { label: 'Food and tobacco roasting baking and drying machine operator and tender', value: '111021' },
  { label: 'Food batchmaker', value: '19204X' },
  { label: 'Food preparation worker', value: '472121' },
  { label: 'Food processing worker', value: '452041' },
  { label: 'Food scientist and technologist', value: '271024' },
  { label: 'Food server', value: '514033' },
  { label: 'Food service manager', value: '395012' },
  { label: 'Forensic science technician', value: '474041' },
  { label: 'Forest and conservation worker', value: '291299' },
  { label: 'Forester', value: '211022' },
  { label: 'Forging machine setter operator and tender metal and plastic', value: '499021' },
  { label: 'Foundry mold and coremaker', value: '493040' },
  { label: 'Funeral attendant', value: '473010' },
  { label: 'Funeral service manager', value: '499098' },
  { label: 'Furniture finisher', value: '519198' },
  { label: 'Gaming and sports book writer and runner', value: '474051' },
  { label: 'Gaming cage worker', value: '499031' },
  { label: 'Gaming dealer', value: '311121' },
  { label: 'Gaming manager', value: '359031' },
  { label: 'Gaming service worker', value: '434081' },
  { label: 'Gaming supervisor', value: '434161' },
  { label: 'Gaming surveillance officer and gaming investigator', value: '113121' },
  { label: 'General maintenance and repair worker', value: '131070' },
  { label: 'General practitioner', value: '49904X' },
  { label: 'Geographer', value: '172110' },
  { label: 'Geological and petroleum technician', value: '113051' },
  { label: 'Geoscientist', value: '537051' },
  { label: 'Glass installer', value: '434199' },
  { label: 'Glazier', value: '151212' },
  { label: 'Graduate teaching assistant', value: '519061' },
  { label: 'Graphic designer', value: '472130' },
  { label: 'Grinding lapping polishing and buffing machine tool setter operator and tender metal and plastic', value: '439041' },
  { label: 'Grounds maintenance worker', value: '413021' },
  { label: 'Hairdresser hairstylist and cosmetologist', value: '132053' },
  { label: 'Hazardous materials removal worker', value: '271025' },
  { label: 'Health and safety engineer', value: '273091' },
  { label: 'Health educator', value: '434111' },
  { label: 'Health information technologist and medical registrar', value: '37201X' },
  { label: 'Health specialties teacher', value: '519071' },
  { label: 'Healthcare social worker', value: '231020' },
  { label: 'Heating air conditioning and refrigeration mechanic and installer', value: '231012' },
  { label: 'Heavy and tractor-trailer truck driver', value: '537062' },
  { label: 'Heavy vehicle and mobile equipment service technician and mechanic', value: '171012' },
  { label: 'Highway maintenance worker', value: '373011' },
  { label: 'Historian', value: '516011' },
  { label: 'Histotechnologist and histologic technician', value: '231011' },
  { label: 'Hoist and winch operator', value: '436012' },
  { label: 'Home appliance repairer', value: '232099' },
  { label: 'Home health aide', value: '111031' },
  { label: 'Host and hostess restaurant lounge and coffee shop', value: '254022' },
  { label: 'Hotel motel and resort desk clerk', value: '434121' },
  { label: 'Housekeeping cleaner', value: '254031' },
  { label: 'Human resources assistant', value: '292061' },
  { label: 'Human resources manager', value: '191099' },
  { label: 'Human resources specialist', value: '434131' },
  { label: 'Hunters and trappers', value: '499094' },
  { label: 'Hydrologist', value: '534010' },
  { label: 'Industrial and refractory machinery mechanic', value: '119081' },
  { label: 'Industrial designer', value: '454020' },
  { label: 'Industrial engineer', value: '131081' },
  { label: 'Industrial machinery mechanic', value: '537063' },
  { label: 'Industrial-organizational psychologist', value: '514041' },
  { label: 'Industrial production manager', value: '292035' },
  { label: 'Industrial truck and tractor operator', value: '372012' },
  { label: 'Information and record clerk', value: '439051' },
  { label: 'Information security analyst', value: '499071' },
  { label: 'Information systems manager', value: '499043' },
  { label: 'Inspector tester sorter sampler and weigher', value: '131111' },
  { label: 'Installation maintenance and repair worker', value: '119199' },
  { label: 'Instructional coordinator', value: '395092' },
  { label: 'Instructional designer', value: '499095' },
  { label: 'Insulation worker', value: '172121' },
  { label: 'Insurance appraiser', value: '112021' },
  { label: 'Insurance claims and policy processing clerk', value: '131161' },
  { label: 'Insurance sales agent', value: '211013' },
  { label: 'Insurance underwriter', value: '319011' },
  { label: 'Interior designer', value: '172131' },
  { label: 'Internist', value: '152021' },
  { label: 'Interpreter and translator', value: '172141' },
  { label: 'Interviewer', value: '274099' },
  { label: 'Janitor and cleaner', value: '273099' },
  { label: 'Jeweler and precious stone and metal worker', value: '119111' },
  { label: 'Judge magistrate judge and magistrate', value: '319092' },
  { label: 'Judicial law clerk', value: '292072' },
  { label: 'Kindergarten teacher', value: '191040' },
  { label: 'Labor relations specialist', value: '436013' },
  { label: 'Laboratory animal caretaker', value: '319094' },
  { label: 'Laborer and freight stock and material mover', value: '131121' },
  { label: 'Landscape architect', value: '211023' },
  { label: 'Landscaping and groundskeeping worker', value: '211014' },
  { label: 'Lathe and turning machine tool setter operator and tender metal and plastic', value: '271026' },
  { label: 'Laundry and dry-cleaning worker', value: '514050' },
  { label: 'Law teacher', value: '435041' },
  { label: 'Lawyer', value: '553010' },
  { label: 'Layout worker', value: '551010' },
  { label: 'Legal assistant and paralegal', value: '554010' },
  { label: 'Legal secretary', value: '499044' },
  { label: 'Legislator', value: '172151' },
  { label: 'Librarian', value: '452090' },
  { label: 'Library assistant and clerical assistant', value: '474090' },
  { label: 'Library technician', value: '292090' },
  { label: 'Licensed practical and licensed vocational nurse', value: '518090' },
  { label: 'Life physical and social science technician', value: '193090' },
  { label: 'Lifeguard and other recreational protective service worker', value: '493090' },
  { label: 'Light truck or delivery services driver', value: '419010' },
  { label: 'Line installer and repairer', value: '514060' },
  { label: 'Loading machine operator', value: '514070' },
  { label: 'Loan officer', value: '519195' },
  { label: 'Locksmith and safe repairer', value: '394031' },
  { label: 'Locomotive engineer', value: '533099' },
  { label: 'Locomotive firer', value: '272041' },
  { label: 'Lodging manager', value: '272042' },
  { label: 'Log grader and scaler', value: '119121' },
  { label: 'Logging equipment operator', value: '151244' },
  { label: 'Logistician', value: '434141' },
  { label: 'Machine feeder and offbearer', value: '273023' },
  { label: 'Machinist', value: '172161' },
  { label: 'Maid and housekeeping cleaner', value: '29203X' },
  { label: 'Mail clerk and mail machine operator except postal service', value: '194051' },
  { label: 'Maintenance and repair worker', value: '291151' },
  { label: 'Maintenance worker', value: '291161' },
  { label: 'Makeup artist theatrical and performance', value: '291171' },
  { label: 'Management analyst', value: '311131' },
  { label: 'Manager', value: '195010' },
  { label: 'Manicurist and pedicurist', value: '291122' },
  { label: 'Manufactured building and mobile home installer', value: '312010' },
  { label: 'Marine engineer and naval architect', value: '439199' },
  { label: 'Marine oiler', value: '439061' },
  { label: 'Market research analyst and marketing specialist', value: '439071' },
  { label: 'Marketing manager', value: '152031' },
  { label: 'Marriage and family therapist', value: '292081' },
  { label: 'Massage therapist', value: '291041' },
  { label: 'Material moving worker', value: '434151' },
  { label: 'Materials engineer', value: '31113X' },
  { label: 'Mathematical science teacher', value: '5120XX' },
  { label: 'Mathematician', value: '21109X' },
  { label: 'Meat poultry and fish cutter and trimmer', value: '27102X' },
  { label: 'Mechanical door repairer', value: '17301X' },
  { label: 'Mechanical drafter', value: '2590XX' },
  { label: 'Mechanical engineer', value: '17302X' },
  { label: 'Mechanical engineering technologist and technician', value: '3930XX' },
  { label: 'Medical and clinical laboratory technologist', value: '4750XX' },
  { label: 'Medical and health services manager', value: '1320XX' },
  { label: 'Medical assistant', value: '37301X' },
  { label: 'Medical equipment preparer', value: '299000' },
  { label: 'Medical records and health information technician', value: '31909X' },
  { label: 'Medical scientist', value: '49909X' },
  { label: 'Medical secretary', value: '1940XX' },
  { label: 'Medical sonographer', value: '51403X' },
  { label: 'Medical transcriptionist', value: '5371XX' },
  { label: 'Meeting convention and event planner', value: '1520XX' },
  { label: 'Mental health counselor', value: '514XXX' },
  { label: 'Mental health and substance abuse social worker', value: '39509X' },
  { label: 'Merchandise displayer and window trimmer', value: '2912XX' },
  { label: 'Metal and plastic machine worker', value: '51919X' },
  { label: 'Metal and plastic worker', value: '5191XX' },
  { label: 'Metal-refining furnace operator and tender', value: '33909X' },
  { label: 'Meter reader utilities', value: '19303X' },
  { label: 'Microbiologist', value: '5340XX' },
  { label: 'Middle school teacher', value: '2530XX' },
  { label: 'Millwright', value: '51609X' },
  { label: 'Mining and geological engineer including mining safety engineer', value: '5360XX' },
  { label: 'Mixing and blending machine setter operator and tender', value: '5170XX' },
  { label: 'Mobile heavy equipment mechanic except engines', value: '519111' },
  { label: 'Model', value: '537064' },
  { label: 'Model maker', value: '472140' },
  { label: 'Mortician undertaker and funeral director', value: '519120' },
  { label: 'Motion picture projectionist', value: '519196' },
  { label: 'Motor vehicle operator', value: '232011' },
  { label: 'Multimedia artist and animator', value: '292043' },
  { label: 'Music director and composer', value: '536021' },
  { label: 'Musical instrument repairer and tuner', value: '333041' },
  { label: 'Musician and singer', value: '412022' },
  { label: 'Natural sciences manager', value: '536061' },
  { label: 'Network and computer systems administrator', value: '433051' },
  { label: 'New accounts clerk', value: '399099' },
  { label: 'News analyst reporter and journalist', value: '132052' },
  { label: 'Nonfarm animal caretaker', value: '119179' },
  { label: 'Nuclear engineer', value: '372021' },
  { label: 'Nuclear medicine technologist', value: '172171' },
  { label: 'Nuclear power reactor operator', value: '291051' },
  { label: 'Nurse anesthetist', value: '319095' },
  { label: 'Nurse midwife', value: '292052' },
  { label: 'Nurse practitioner', value: '319097' },
  { label: 'Nursing assistant', value: '274021' },
  { label: 'Nutritionist', value: '519151' },
  { label: 'Obstetrician and gynecologist', value: '192099' },
  { label: 'Occupational health and safety specialist', value: '291123' },
  { label: 'Occupational health and safety technician', value: '312020' },
  { label: 'Occupational therapist', value: '291071' },
  { label: 'Occupational therapy aide', value: '472151' },
  { label: 'Occupational therapy assistant', value: '472161' },
  { label: 'Office and administrative support worker', value: '472152' },
  { label: 'Office clerk', value: '291081' },
  { label: 'Operating engineer and other construction equipment operator', value: '333050' },
  { label: 'Operations research analyst', value: '435051' },
  { label: 'Ophthalmic laboratory technician', value: '435052' },
  { label: 'Optician dispensing', value: '435053' },
  { label: 'Optometrist', value: '119131' },
  { label: 'Order clerk', value: '251000' },
  { label: 'Order filler', value: '518010' },
  { label: 'Orthodontist', value: '499060' },
  { label: 'Orthotist and prosthetist', value: '515111' },
  { label: 'Packaging and filling machine operator and tender', value: '252010' },
  { label: 'Painter', value: '516021' },
  { label: 'Painter construction and maintenance', value: '515113' },
  { label: 'Paper goods machine setter operator and tender', value: '515112' },
  { label: 'Paralegal and legal assistant', value: '339021' },
  { label: 'Paramedic', value: '211092' },
  { label: 'Parking enforcement worker', value: '433061' },
  { label: 'Parking lot attendant', value: '272012' },
  { label: 'Parts salesperson', value: '435061' },
  { label: 'Paving surfacing and tamping equipment operator', value: '131082' },
  { label: 'Payroll and timekeeping clerk', value: '439081' },
  { label: 'Pediatrician', value: '132020' },
  { label: 'Personal care aide', value: '119141' },
  { label: 'Personal care and service worker', value: '292053' },
  { label: 'Personal financial advisor', value: '112030' },
  { label: 'Pest control worker', value: '273031' },
  { label: 'Petroleum engineer', value: '435031' },
  { label: 'Petroleum pump system operator', value: '537070' },
  { label: 'Pharmacist', value: '131023' },
  { label: 'Pharmacy aide', value: '113061' },
  { label: 'Pharmacy technician', value: '291124' },
  { label: 'Philosophy and religion teacher', value: '492020' },
  { label: 'Photographer', value: '292034' },
  { label: 'Photographic process worker and processing machine operator', value: '291224' },
  { label: 'Physical therapist', value: '534031' },
  { label: 'Physical therapist aide', value: '474061' },
  { label: 'Physical therapist assistant', value: '419020' },
  { label: 'Physician', value: '434171' },
  { label: 'Physician assistant', value: '291125' },
  { label: 'Physicist', value: '399032' },
  { label: 'Pile-driver operator', value: '537081' },
  { label: 'Pipefitter and steamfitter', value: '291141' },
  { label: 'Plasterer and stucco mason', value: '211015' },
  { label: 'Plumber', value: '472171' },
  { label: 'Podiatrist', value: '212099' },
  { label: 'Police and detective', value: '434181' },
  { label: 'Police officer', value: '399041' },
  { label: 'Political scientist', value: '291126' },
  { label: 'Postal service clerk', value: '412031' },
  { label: 'Postal service mail carrier', value: '499096' },
  { label: 'Postal service mail sorter processor and processing machine operator', value: '472181' },
  { label: 'Postmaster and mail superintendent', value: '475071' },
  { label: 'Postsecondary teacher', value: '535011' },
  { label: 'Power plant operator', value: '419099' },
  { label: 'Power distributor and dispatcher', value: '419031' },
  { label: 'Precision instrument and equipment repairer', value: '112022' },
  { label: 'Prepress technician and worker', value: '413091' },
  { label: 'Preschool teacher', value: '414010' },
  { label: 'Presser textile garment and related materials', value: '517041' },
  { label: 'Print binding and finishing worker', value: '533051' },
  { label: 'Printing press operator', value: '339094' },
  { label: 'Private detective and investigator', value: '193034' },
  { label: 'Probation officer and correctional treatment specialist', value: '252030' },
  { label: 'Procurement clerk', value: '436014' },
  { label: 'Producer and director', value: '413031' },
  { label: 'Production planning and expediting clerk', value: '492098' },
  { label: 'Production worker', value: '339030' },
  { label: 'Property real estate and community association manager', value: '474071' },
  { label: 'Psychiatric aide', value: '516031' },
  { label: 'Psychiatric technician', value: '472211' },
  { label: 'Psychiatrist', value: '535020' },
  { label: 'Psychologist', value: '535031' },
  { label: 'Public address system and other announcer', value: '435071' },
  { label: 'Public relations manager', value: '516040' },
  { label: 'Public relations specialist', value: '533053' },
  { label: 'Pump operator', value: '395094' },
  { label: 'Purchasing agent', value: '493050' },
  { label: 'Purchasing manager', value: '119151' },
  { label: 'Quality control analyst', value: '211093' },
  { label: 'Quality control inspector', value: '194061' },
  { label: 'Radiation therapist', value: '211029' },
  { label: 'Radio and telecommunications equipment installer and repairer', value: '193041' },
  { label: 'Radiologic technologist and technician', value: '151252' },
  { label: 'Rail car repairer', value: '151253' },
  { label: 'Rail transportation worker', value: '472231' },
  { label: 'Railroad brake signal and switch operator', value: '252050' },
  { label: 'Railroad conductor and yardmaster', value: '291127' },
  { label: 'Real estate broker', value: '518021' },
  { label: 'Real estate sales agent', value: '439111' },
  { label: 'Receptionist and information clerk', value: '152041' },
  { label: 'Recreation worker', value: '537065' },
  { label: 'Recreational therapist', value: '472221' },
  { label: 'Refuse and recyclable material collector', value: '512041' },
  { label: 'Registered nurse', value: '211011' },
  { label: 'Rehabilitation counselor', value: '391000' },
  { label: 'Reinforcing iron and rebar worker', value: '531000' },
  { label: 'Religious worker', value: '291240' },
  { label: 'Rental clerk', value: '292055' },
  { label: 'Reporter and correspondent', value: '173031' },
  { label: 'Residential advisor', value: '171020' },
  { label: 'Respiratory therapist', value: '193022' },
  { label: 'Respiratory therapy technician', value: '432011' },
  { label: 'Retail salesperson', value: '516050' },
  { label: 'Rigger', value: '132081' },
  { label: 'Rock splitter', value: '533054' },
  { label: 'Roof bolter mining', value: '132082' },
  { label: 'Roofer', value: '259040' },
  { label: 'Rotary drill operator oil and gas', value: '273042' },
  { label: 'Roustabout oil and gas', value: '499052' },
  { label: 'Sales engineer', value: '419041' },
  { label: 'Sales manager', value: '432021' },
  { label: 'Sales representative', value: '274030' },
  { label: 'Sales worker', value: '433071' },
  { label: 'Sawing machine setter operator and tender', value: '516060' },
  { label: 'School psychologist', value: '291129' },
  { label: 'School teacher', value: '519197' },
  { label: 'Secretary and administrative assistant', value: '232093' },
  { label: 'Security and fire alarm systems installer', value: '514111' },
  { label: 'Security guard', value: '397010' },
  { label: 'Self-enrichment teacher', value: '113131' },
  { label: 'Semiconductor processor', value: '131151' },
  { label: 'Service unit operator', value: '533052' },
  { label: 'Set and exhibit designer', value: '536051' },
  { label: 'Sewer', value: '339093' },
  { label: 'Sewing machine operator', value: '536030' },
  { label: 'Sheet metal worker', value: '113071' },
  { label: 'Sheriff and deputy sheriff', value: '413041' },
  { label: 'Ship engineer', value: '373013' },
  { label: 'Shipping receiving and inventory clerk', value: '253041' },
  { label: 'Shoe and leather worker', value: '272023' },
  { label: 'Shoe machine operator and tender', value: '475040' },
  { label: 'Signal and track switch repairer', value: '999999' },
  { label: 'Skincare specialist', value: '516093' },
  { label: 'Small engine mechanic', value: '193051' },
  { label: 'Social and community service manager', value: '393031' },
  { label: 'Social science research assistant', value: '291131' },
  { label: 'Social scientist', value: '319096' },
  { label: 'Social service specialist', value: '292056' },
  { label: 'Social worker', value: '353031' },
  { label: 'Sociologist', value: '518031' },
  { label: 'Software developer', value: '151255' },
  { label: 'Software quality assurance analyst and tester', value: '151254' },
  { label: 'Soil and plant scientist', value: '435111' },
  { label: 'Solar photovoltaic installer', value: '514120' },
  { label: 'Sorter', value: '131022' },
  { label: 'Sound engineering technician', value: '499081' },
  { label: 'Special education teacher', value: '517042' },
  { label: 'Speech-language pathologist', value: '439022' },
  { label: 'Stationary engineer and boiler operator', value: '273043' },
  { label: 'Statistician', value: '211011' },
  { label: 'Stock clerk and order filler', value: '292031' },
  { label: 'Stonemason', value: '435031' },
  { label: 'Structural iron and steel worker', value: '537070' },
  { label: 'Structural metal fabricator and fitter', value: '131023' },
  { label: 'Substance abuse and behavioral disorder counselor', value: '113061' },
  { label: 'Subway and streetcar operator', value: '291124' },
  { label: 'Supervisor', value: '492020' },
  { label: 'Supervisor of food preparation and serving workers', value: '292034' },
  { label: 'Supervisor of personal care and service workers', value: '291224' },
  { label: 'Supervisor of production and operating workers', value: '534031' },
  { label: 'Supervisor of sales workers', value: '474061' },
  { label: 'Surgical technologist', value: '419020' },
  { label: 'Survey researcher', value: '434171' },
  { label: 'Surveying and mapping technician', value: '291125' },
  { label: 'Surveyor', value: '399032' },
  { label: 'Switchboard operator including answering service', value: '537081' },
  { label: 'Tailor dressmaker and custom sewer', value: '291141' },
  { label: 'Tank car truck and ship loader', value: '211015' },
  { label: 'Tax examiner collector and revenue agent', value: '472171' },
  { label: 'Tax preparer', value: '212099' },
  { label: 'Taxi driver', value: '434181' },
  { label: 'Teacher', value: '399041' },
  { label: 'Teacher assistant', value: '291126' },
  { label: 'Team assembler', value: '412031' },
  { label: 'Technical writer', value: '499096' },
  { label: 'Telecommunications equipment installer and repairer', value: '472181' },
  { label: 'Telecommunications line installer and repairer', value: '475071' },
  { label: 'Telemarketer', value: '535011' },
  { label: 'Telephone operator', value: '419099' },
  { label: 'Teller', value: '419031' },
  { label: 'Terrazzo worker and finisher', value: '112022' },
  { label: 'Textile bleaching and dyeing machine operator and tender', value: '413091' },
  { label: 'Textile cutting machine setter operator and tender', value: '414010' },
  { label: 'Textile knitting and weaving machine setter operator and tender', value: '517041' },
  { label: 'Textile worker', value: '533051' },
  { label: 'Therapist', value: '339094' },
  { label: 'Tile and marble setter', value: '193034' },
  { label: 'Timing device assembler and adjuster', value: '252030' },
  { label: 'Tire changer', value: '436014' },
  { label: 'Tire repairer and changer', value: '413031' },
  { label: 'Title examiner abstractor and searcher', value: '492098' },
  { label: 'Tool and die maker', value: '339030' },
  { label: 'Tool grinder filer and sharpener', value: '474071' },
  { label: 'Tour guide', value: '516031' },
  { label: 'Tractor-trailer truck driver', value: '472211' },
  { label: 'Training and development manager', value: '535020' },
  { label: 'Training and development specialist', value: '535031' },
  { label: 'Transit and railroad police', value: '435071' },
  { label: 'Transportation attendant', value: '516040' },
  { label: 'Transportation inspector', value: '533053' },
  { label: 'Transportation security screener', value: '395094' },
  { label: 'Transportation worker', value: '493050' },
  { label: 'Travel agent', value: '119151' },
  { label: 'Travel guide', value: '211093' },
  { label: 'Tree trimmer and pruner', value: '194061' },
  { label: 'Tutor', value: '211029' },
  { label: 'Umpire referee and other sports official', value: '193041' },
  { label: 'Underground mining machine operator', value: '151252' },
  { label: 'Upholsterer', value: '151253' },
  { label: 'Urban and regional planner', value: '472231' },
  { label: 'Usher lobby attendant and ticket taker', value: '252050' },
  { label: 'Veterinarian', value: '291127' },
  { label: 'Veterinary assistant and laboratory animal caretaker', value: '518021' },
  { label: 'Veterinary technologist and technician', value: '439111' },
  { label: 'Waiter or waitress', value: '152041' },
  { label: 'Water and wastewater treatment plant and system operator', value: '537065' },
  { label: 'Web and digital interface designer', value: '472221' },
  { label: 'Web developer', value: '512041' },
  { label: 'Weigher measurer checker and sampler recordkeeping', value: '211011' },
  { label: 'Welding soldering and brazing worker', value: '514120' },
  { label: 'Wholesale and retail buyer except farm products', value: '131022' },
  { label: 'Wind turbine service technician', value: '499081' },
  { label: 'Woodworking machine setter operator and tender except sawing', value: '517042' },
  { label: 'Word processor and typist', value: '439022' },
  { label: 'Writer and author', value: '273043' },
]
